version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=wisdom

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=wisdom
      - USE_DOCKER=yes
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis

  redis:
    image: redis:latest

  signalmaster:
    build: https://github.com/andyet/signalmaster.git
    ports:
      - "8888:8888"




