# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 18:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0030_settings_max_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Group ID'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_rounds',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='score_lambda',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
