# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0032_slidervalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidervalue',
            name='interactive_round',
        ),
        migrations.RemoveField(
            model_name='slidervalue',
            name='user',
        ),
        migrations.DeleteModel(
            name='SliderValue',
        ),
    ]
