# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Linked User ID'),
        ),
    ]
