# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('round', '0015_auto_20170131_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('this_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='round.Round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
