# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0016_slidervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidervalue',
            name='round_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
