# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0018_auto_20170131_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidervalue',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
